version: '3.8'
services:
  postgres:
    container_name: pg_container
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: transcendence
    ports:
      - "5432:5432"
  node:
    build:
      context: ./backend/.
      dockerfile: Dockerfile
    container_name: ts_node
    restart: always
    ports:
      - "10087:10087"
    depends_on:
      - postgres
    env_file:
      - ./.env
  nginx:
    container_name: ts_nginx
    build:
      context: ./frontend/.
      dockerfile: Dockerfile
    ports:
      - "10086:80"
    restart: always
    env_file:
      - ./.env
